//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LufthavnsAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public string PortOne { get; set; }
        public string PortTwo { get; set; }
        public int Airline_Id { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
    }
}
